


name: PY_Test

on:
  workflow_dispatch:

permissions:
  contents: read
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9  # Change this to your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./src  # Change this to your project's root directory

    - name: Deploy
      run: |
        python src/app.py
